[project]
name = "the-art-of-readable-code"
version = "0.1.0"
description = "ğŸ¼ Designing and Implementing a â€œMinute/Hour Counterâ€"
readme = "README.md"
authors = [
    { name = "cassiobotaro", email = "cassiobotaro@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.12"
mypy = "^1.16.0"

